#!/usr/bin/perl

use strict;
use warnings;

use WWW::Mechanize;
use FileHandle;
use File::Basename;

my $script_id = 453;

my $mech = WWW::Mechanize->new(autocheck => 1);
my $dirname = dirname($0);

sub GetPassword() {
	my @credentials;
	my $passfile = "$ENV{HOME}/.vimonline_credentials"; # line 1: username, line 2: password
	my $pass = FileHandle->new($passfile, 'r') or die "Can't open credential file: $passfile\n";
	my $line;
	while ($line = <$pass>) {
		chomp($line);
		push(@credentials, $line);
	}
	$pass->close;
	return @credentials;
}

sub GetRequiredVersion() {
	my $pluginfile = "$dirname/ftplugin/html/HTML.vim";
	my $plugin = FileHandle->new($pluginfile, 'r') or die "Can't open plugin file: $pluginfile\n";
	my $line;

	while ($line = <$plugin>) {
		chomp($line);
		if ($line =~ m/^if v:version < ([0-9]+)$/) {
			$plugin->close;
			return int($1 / 100) . '.' . ($1 % 100);
		}
	}

	return '';
}

sub GetVersion() {
	my $versionfile = "$dirname/version";
	my $version;
	my $ver = FileHandle->new($versionfile, 'r') or die "Can't open version file: $versionfile\n";
	chomp($version = <$ver>);
	$ver->close();
	return $version;
}

sub GetComment() {
	my $lines;
	print "Enter a comment, Ctrl-D to finish:\n";
	while (my $line = <STDIN>) {
		$lines .= $line;
	}
	return $lines;
}

my $archive = "$dirname/HTML.zip";
my $script_version = GetVersion();
my $version_comment = GetComment();

die "Must provide a comment\n" unless $version_comment;

my @user_credentials = GetPassword();
my $vim_version_required = GetRequiredVersion();

die "Can't obtain minumum required version of Vim" unless $vim_version_required;

die "Credential file must be two lines\n" unless scalar @user_credentials == 2;

die "Zip archive not found or unreadable\n" unless (-e $archive && -r $archive);

print "Logging in...\n";

$mech->get('http://www.vim.org/login.php');

$mech->submit_form(
	form_name => 'login',
	with_fields => {
		userName => $user_credentials[0],
		password => $user_credentials[1],
	},
);

$mech->get("http://www.vim.org/scripts/script.php?script_id=$script_id");

print "Uploading...\n";

$mech->follow_link(text => 'upload new version');
$mech->form_name('script');
$mech->field(script_file => $archive);
$mech->field(vim_version => $vim_version_required);
$mech->field(script_version => $script_version);
$mech->field(version_comment => $version_comment);
$mech->click_button(value => 'upload');

print "Uploaded\n";
