name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: rhysd/action-setup-vim@v1
      with:
        version: v9.2.0

    - name: Create archive
      run: make zip

    - name: Run tests
      run: make test
